Vagrant.configure("2") do |config|
  # General VM configuration
  config.vm.box = "ubuntu/bionic64"

  # Configuration for Web VM
  config.vm.define "web_vm" do |web|
    web.vm.hostname = "web-vm"
    web.vm.network "private_network", ip: "192.168.56.101"
    web.vm.network "forwarded_port", guest: 22, host: 2200, id: "ssh"
    web.vm.synced_folder ".", "/vagrant", type: "virtualbox"
    web.vm.provision "ansible" do |ansible|
      ansible.playbook = "../ansible/shanzeh_web.yml"
    end
  end

  # Configuration for API VM
  config.vm.define "api_vm" do |api|
    api.vm.hostname = "api-vm"
    api.vm.network "private_network", ip: "192.168.56.102"
    api.vm.network "forwarded_port", guest: 22, host: 2201, id: "ssh"
    api.vm.synced_folder ".", "/vagrant", type: "virtualbox"
    api.vm.provision "ansible" do |ansible|
      ansible.playbook = "../ansible/sohaib_api.yml"
    end
  end

  # Configuration for Android VM
  config.vm.define "android_vm" do |android|
    android.vm.hostname = "android-vm"
    android.vm.network "private_network", ip: "192.168.56.103"
    android.vm.network "forwarded_port", guest: 22, host: 2202, id: "ssh"
    android.vm.synced_folder ".", "/vagrant", type: "virtualbox"
    android.vm.provision "ansible" do |ansible|
      ansible.playbook = "../ansible/eesha_android.yml"
    end
  end
end